services:
  db:
    image: postgres:16
    container_name: flowbon-db
    restart: always
    environment:
      POSTGRES_USER: flowbon
      POSTGRES_PASSWORD: flowbon123
      POSTGRES_DB: flowbon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: flowbon-backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql://flowbon:flowbon123@db:5432/flowbon
      APP_NAME: FlowBon
      APP_ENV: local # Reste en local pour utiliser le canal SMTP
      FRONTEND_URL: http://localhost
      # URLs autorisées par CORS (séparées par des virgules)
      # Ajouter l'URL ngrok ici lors des tests en ligne
      FRONTEND_URLS: http://localhost,http://127.0.0.1,https://*.ngrok-free.app,https://*.ngrok-free.dev,https://*.ngrok.io

      # Configuration SMTP de GMAIL :
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: bawatcharesamoudine@gmail.com
      SMTP_PASSWORD: lwyg biuu tqvi yzhk


  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=/api
    container_name: flowbon-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - INTERNAL_API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=/api

  nginx:
    image: nginx:latest
    container_name: flowbon-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  maildev:
    image: maildev/maildev
    container_name: flowbon-maildev
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  pgdata:

