"""phase4_multitenant_projects

Revision ID: 0959b9996105
Revises: 2f78145c2329
Create Date: 2026-05-22 00:03:51.797723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0959b9996105'
down_revision: Union[str, Sequence[str], None] = '2f78145c2329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('user_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company')
    )
    op.create_index(op.f('ix_user_companies_company_id'), 'user_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_companies_id'), 'user_companies', ['id'], unique=False)
    op.create_index(op.f('ix_user_companies_user_id'), 'user_companies', ['user_id'], unique=False)
    op.add_column('expense_requests', sa.Column('accounting_account_id', sa.UUID(), nullable=True))
    op.add_column('expense_requests', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expense_requests_accounting_account_id'), 'expense_requests', ['accounting_account_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_project_id'), 'expense_requests', ['project_id'], unique=False)
    op.create_foreign_key(None, 'expense_requests', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'expense_requests', 'accounting_accounts', ['accounting_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_requests', type_='foreignkey')
    op.drop_constraint(None, 'expense_requests', type_='foreignkey')
    op.drop_index(op.f('ix_expense_requests_project_id'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_accounting_account_id'), table_name='expense_requests')
    op.drop_column('expense_requests', 'project_id')
    op.drop_column('expense_requests', 'accounting_account_id')
    op.drop_index(op.f('ix_user_companies_user_id'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_id'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_company_id'), table_name='user_companies')
    op.drop_table('user_companies')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
