"""add company currency and user backup roles

Revision ID: 23f15ab95abd
Revises: d7411a3ad202
Create Date: 2026-05-17 19:59:54.648756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f15ab95abd'
down_revision: Union[str, Sequence[str], None] = 'd7411a3ad202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency', sa.String(), server_default='XOF', nullable=False))
    op.add_column('users', sa.Column('is_backup_manager', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_backup_accountant', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_backup_accountant')
    op.drop_column('users', 'is_backup_manager')
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###
