"""add_ledger_entries

Revision ID: 2f78145c2329
Revises: 4d5ca515ed50
Create Date: 2026-05-21 23:40:58.487762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f78145c2329'
down_revision: Union[str, Sequence[str], None] = '4d5ca515ed50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('accounting_account_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accounting_account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_accounting_account_id'), 'ledger_entries', ['accounting_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_company_id'), 'ledger_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_id'), 'ledger_entries', ['reference_id'], unique=False)
    op.add_column('cash_registers', sa.Column('accounting_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cash_registers', 'accounting_accounts', ['accounting_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cash_registers', type_='foreignkey')
    op.drop_column('cash_registers', 'accounting_account_id')
    op.drop_index(op.f('ix_ledger_entries_reference_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_company_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_accounting_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
