"""add_treasury_account_type

Revision ID: 4d5ca515ed50
Revises: fe1f05217e89
Create Date: 2026-05-21 23:31:31.694419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5ca515ed50'
down_revision: Union[str, Sequence[str], None] = 'fe1f05217e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('cash_registers', sa.Column('account_type', sa.String(), server_default='CASH', nullable=False))
    op.add_column('cash_registers', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('cash_registers', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('cash_registers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_registers', 'is_active')
    op.drop_column('cash_registers', 'account_number')
    op.drop_column('cash_registers', 'bank_name')
    op.drop_column('cash_registers', 'account_type')
    # ### end Alembic commands ###
