"""add trial expires at to company

Revision ID: 5d07979d9277
Revises: b59dd4c90a4f
Create Date: 2026-05-17 23:04:13.040491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d07979d9277'
down_revision: Union[str, Sequence[str], None] = 'b59dd4c90a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('trial_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'trial_expires_at')
    # ### end Alembic commands ###
