"""Add company_type

Revision ID: 9518b9f18cfc
Revises: a1b2c3d4e5f6
Create Date: 2026-05-23 22:26:41.586079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9518b9f18cfc'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_type', sa.String(), nullable=False))
    op.add_column('expense_requests', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_constraint(op.f('treasury_transactions_reference_key'), 'treasury_transactions', type_='unique')
    op.drop_index(op.f('ix_treasury_transactions_reference'), table_name='treasury_transactions')
    op.create_index(op.f('ix_treasury_transactions_reference'), 'treasury_transactions', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treasury_transactions_reference'), table_name='treasury_transactions')
    op.create_index(op.f('ix_treasury_transactions_reference'), 'treasury_transactions', ['reference'], unique=False)
    op.create_unique_constraint(op.f('treasury_transactions_reference_key'), 'treasury_transactions', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_column('expense_requests', 'tax_amount')
    op.drop_column('companies', 'company_type')
    # ### end Alembic commands ###
