"""add_category_id_to_advance_request

Revision ID: 9f2425e8251e
Revises: 5d07979d9277
Create Date: 2026-05-18 08:38:13.946669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2425e8251e'
down_revision: Union[str, Sequence[str], None] = '5d07979d9277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advance_requests', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'advance_requests', 'expense_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advance_requests', type_='foreignkey')
    op.drop_column('advance_requests', 'category_id')
    # ### end Alembic commands ###
