"""add_expense_category

Revision ID: a9de6e238858
Revises: 1465058a3d77
Create Date: 2026-05-17 09:09:49.392664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9de6e238858'
down_revision: Union[str, Sequence[str], None] = '1465058a3d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    
    op.add_column('expense_requests', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_expense_requests_category_id', 'expense_requests', 'expense_categories', ['category_id'], ['id'])
    
    # Data migration: Seed default categories for all existing companies and map expenses
    bind = op.get_bind()
    import uuid
    from datetime import datetime

    companies = bind.execute(sa.text("SELECT id FROM companies")).fetchall()
    
    default_names = [
        "Transport", "Hébergement", "Repas", "Fournitures de bureau",
        "Informatique & Logiciels", "Télécom & Internet", "Formation", "Frais divers"
    ]

    for company in companies:
        company_id = company[0]
        for name in default_names:
            cat_id = uuid.uuid4()
            bind.execute(sa.text(
                "INSERT INTO expense_categories (id, company_id, name, is_active, created_at, updated_at) "
                "VALUES (:id, :company_id, :name, true, :now, :now)"
            ), {"id": cat_id, "company_id": company_id, "name": name, "now": datetime.utcnow()})
            
            bind.execute(sa.text(
                "UPDATE expense_requests SET category_id = :cat_id "
                "WHERE company_id = :company_id AND LOWER(category) = LOWER(:name)"
            ), {"cat_id": cat_id, "company_id": company_id, "name": name})

    for company in companies:
        company_id = company[0]
        frais_divers = bind.execute(sa.text(
            "SELECT id FROM expense_categories WHERE company_id = :company_id AND name = 'Frais divers'"
        ), {"company_id": company_id}).fetchone()
        if frais_divers:
            frais_divers_id = frais_divers[0]
            bind.execute(sa.text(
                "UPDATE expense_requests SET category_id = :frais_divers_id "
                "WHERE company_id = :company_id AND category_id IS NULL"
            ), {"frais_divers_id": frais_divers_id, "company_id": company_id})

    # Set non-nullable
    op.alter_column('expense_requests', 'category_id', nullable=False)
    op.drop_column('expense_requests', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_requests', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Backfill category name string from category_id relation
    bind = op.get_bind()
    bind.execute(sa.text(
        "UPDATE expense_requests er SET category = ec.name "
        "FROM expense_categories ec WHERE er.category_id = ec.id"
    ))
    
    op.alter_column('expense_requests', 'category', nullable=False)
    op.drop_constraint('fk_expense_requests_category_id', 'expense_requests', type_='foreignkey')
    op.drop_column('expense_requests', 'category_id')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
