"""Add cashier caisse association

Revision ID: ac61304ccb73
Revises: b0f7b5d0ed28
Create Date: 2026-05-20 18:32:46.952687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac61304ccb73'
down_revision: Union[str, Sequence[str], None] = 'b0f7b5d0ed28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_caisse_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cash_register_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'cash_register_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashier_caisse_association')
    # ### end Alembic commands ###
