"""add_cashier_role_and_segregation

Revision ID: b0f7b5d0ed28
Revises: c1e5fab4a573
Create Date: 2026-05-20 01:03:33.150872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f7b5d0ed28'
down_revision: Union[str, Sequence[str], None] = 'c1e5fab4a573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('has_separate_cashier', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_backup_cashier', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_backup_cashier')
    op.drop_column('companies', 'has_separate_cashier')
    # ### end Alembic commands ###
