"""add_document_sequences_and_reference_numbers

Revision ID: f63baa54bbe1
Revises: 0959b9996105
Create Date: 2026-05-22 00:59:54.458614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63baa54bbe1'
down_revision: Union[str, Sequence[str], None] = '0959b9996105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_type', 'year', name='uq_document_sequence')
    )
    op.create_index(op.f('ix_document_sequences_company_id'), 'document_sequences', ['company_id'], unique=False)
    op.add_column('advance_requests', sa.Column('reference_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_advance_requests_reference_number'), 'advance_requests', ['reference_number'], unique=True)
    op.add_column('cash_transactions', sa.Column('reference_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_cash_transactions_reference_number'), 'cash_transactions', ['reference_number'], unique=True)
    op.add_column('ledger_entries', sa.Column('reference_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_ledger_entries_reference_number'), 'ledger_entries', ['reference_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_reference_number'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'reference_number')
    op.drop_index(op.f('ix_cash_transactions_reference_number'), table_name='cash_transactions')
    op.drop_column('cash_transactions', 'reference_number')
    op.drop_index(op.f('ix_advance_requests_reference_number'), table_name='advance_requests')
    op.drop_column('advance_requests', 'reference_number')
    op.drop_index(op.f('ix_document_sequences_company_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
