"""add_scopes_and_departments

Revision ID: fe1f05217e89
Revises: 5b5ae167d083
Create Date: 2026-05-21 22:54:06.934656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1f05217e89'
down_revision: Union[str, Sequence[str], None] = '5b5ae167d083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_department')
    )
    op.create_index(op.f('ix_user_departments_department_id'), 'user_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_departments_id'), 'user_departments', ['id'], unique=False)
    op.create_index(op.f('ix_user_departments_user_id'), 'user_departments', ['user_id'], unique=False)
    op.create_index(op.f('ix_accounting_accounts_company_id'), 'accounting_accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_unique_constraint('uq_department_company_name', 'departments', ['company_id', 'name'])
    op.create_index(op.f('ix_expense_category_account_mappings_accounting_account_id'), 'expense_category_account_mappings', ['accounting_account_id'], unique=False)
    op.create_index(op.f('ix_expense_category_account_mappings_company_id'), 'expense_category_account_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_expense_category_account_mappings_expense_category_id'), 'expense_category_account_mappings', ['expense_category_id'], unique=False)
    op.add_column('expense_requests', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expense_requests_department_id'), 'expense_requests', ['department_id'], unique=False)
    op.create_foreign_key(None, 'expense_requests', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('scope_type', sa.String(), server_default='GLOBAL', nullable=False))
    op.add_column('users', sa.Column('scope_id', sa.UUID(), nullable=True))
    
    # Data migration: copy existing department_id to user_departments and to expense_requests
    op.execute("""
        INSERT INTO user_departments (id, user_id, department_id, is_primary, created_at)
        SELECT gen_random_uuid(), id, department_id, true, NOW()
        FROM users
        WHERE department_id IS NOT NULL
    """)
    op.execute("""
        UPDATE expense_requests er
        SET department_id = u.department_id
        FROM users u
        WHERE er.user_id = u.id AND u.department_id IS NOT NULL
    """)

    # Data migration: scope_id mapping if users had department_id and are managers
    op.execute("""
        UPDATE users
        SET scope_type = 'DEPARTMENT', scope_id = department_id
        WHERE role = 'manager' AND department_id IS NOT NULL
    """)

    op.drop_constraint('fk_users_department_id', 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_department_id'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_column('users', 'scope_id')
    op.drop_column('users', 'scope_type')
    op.drop_constraint(None, 'expense_requests', type_='foreignkey')
    op.drop_index(op.f('ix_expense_requests_department_id'), table_name='expense_requests')
    op.drop_column('expense_requests', 'department_id')
    op.drop_index(op.f('ix_expense_category_account_mappings_expense_category_id'), table_name='expense_category_account_mappings')
    op.drop_index(op.f('ix_expense_category_account_mappings_company_id'), table_name='expense_category_account_mappings')
    op.drop_index(op.f('ix_expense_category_account_mappings_accounting_account_id'), table_name='expense_category_account_mappings')
    op.drop_constraint('uq_department_company_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_accounting_accounts_company_id'), table_name='accounting_accounts')
    op.drop_index(op.f('ix_user_departments_user_id'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_id'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_department_id'), table_name='user_departments')
    op.drop_table('user_departments')
    # ### end Alembic commands ###
